name: Build Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: autogen
        run: ./autogen.sh
      - name: configure
        run: ./configure --enable-keygen --enable-cryptonly --enable-ssh
      - name: make
        run: make
      - name: make check
        run: make check
      - uses: actions/upload-artifact@v2
        with:
          name: wolfssl-linux
          path: src/.libs/
          if-no-files-found: error
