name: Build Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_CONFIGURATION: Release

jobs:
  build:
    strategy:
      matrix:
        solution: ["", "64", "-ntru"]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: "[9.0,10.0)"

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore wolfssl${{matrix.solution}}.sln

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} -toolsversion:3.5 wolfssl${{matrix.solution}}.sln
      - uses: actions/upload-artifact@v2
        with:
          name: wolfssl-windows${{matrix.solution}}
          path: src/.libs/
